### ISSUE TITLE
My experience using tezbridge :-/

### ISSUE THREAD

**Issue by murbard** [tezbridge/tezbridge-web#1]
1. I head over to tezbridge.com
2. It says Loading protocol
3. Nothing else happens
4. Nothing is happening I go to close the browser window
5. Wait no, it says "Loading protocol Pt24m4xi" now
6. I don't recognize this protocol hash
7. I wait, nothing happens
8. I give up.

**Comment by catsigma** [comment]
The issue was due to the failure handling of RPC node protocol detection since the previously used RPC node from tezrpc.me is down. 
Should be fixed now.

**Comment by murbard** [comment]
The new RPC node is unlikely to be reliable

**Comment by catsigma** [comment]
I'll make a RPC node selector later for users to choose when the current RPC node is down.
