### ISSUE TITLE
Support selecting RPC Node programmatically from an app

### ISSUE THREAD

**Issue by mchaver** [tezbridge/tezbridge-web#2]
Currently you can manually select a node via the web interface. It would be nice if there was a function in `tezbridge.set_host` that let's you do this via an application.

**Comment by catsigma** [comment]
I think it's not safe for users to accept a function like this. 
But you can use 
```
tezbridge.request({
  method: 'set_host',
  host: YOUR HOST
})
```
to ask the permission to change host for the users.
